### ISSUE TITLE
Programs not running and no manual zone control

### ISSUE THREAD

**Issue by andyvk5** [petergridge/Irrigation-V5#102]
After upgrading to V2024.12 programs not running and unable to start zones manually. looking at the logs there is an error being generated by the function "async_stop_programs" called from async_turn_on

the state is not being returned correctly. log example below.

V2024.12.

`2024-12-27 04:38:35.526 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/irrigationprogram/program.py", line 542, in async_turn_on
    await async_stop_programs(self._hass, self.name)
  File "/config/custom_components/irrigationprogram/__init__.py", line 237, in async_stop_programs
    if hass.states.get(device).is_on:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'State' object has no attribute 'is_on'`

the condition to check if the state is "on" causing the issue.  

I have resolved it by changing to         `if hass.states.get(device).state == 'on':` [full function below] 

my question: should other states be checked to cause a program to be stopped or this changes to not "off".

not quite sure of the various states,

cheers andrew

`async def async_stop_programs(hass,ignore_program):
    '''Stop all running programs.'''

    for n, data in enumerate(hass.data[DOMAIN].values()):
        if data.get(ATTR_NAME) == ignore_program:
            continue
        device = SWITCH_ID_FORMAT.format(slugify(data.get(ATTR_NAME,'unknown')))
        servicedata = {ATTR_ENTITY_ID: device}
        #warn if the program is terminated
        await asyncio.sleep(n)
        if hass.states.get(device).state == 'on':
            async_create(
                hass,
                message=f"Trial Irrigation Program {data.get(ATTR_NAME)} terminated by {ignore_program}",
                title="Irrigation Controller"
            )
            await hass.services.async_call(CONST_SWITCH, SERVICE_TURN_OFF, servicedata)`

**Comment by petergridge** [comment]
Hi, Sorry for the slow response.
- Do you have two programs configured?
- Can you provide the diagnostic output for the programs.

**Comment by petergridge** [comment]
Latest version has implemented the fix. 

Cheers

**Comment by andyvk5** [comment]
No worries, I’ll give it a go in the next day or two.

Sorry for not getting back to you on the additional logs and number of
programs.

I am running multiple programs. My lawns now use sunrise with and offset,
large garden beds sunset with an offset. And pot plants on a timer.

Keep up the good work.
 Thanks

Andrew.
