### ISSUE TITLE
Nothing works after the V2025.01 update

### ISSUE THREAD

**Issue by omenukas** [petergridge/Irrigation-V5#103]
After updating to V2025.01, all Irrigation cards disappeared. So impressive that it made the entire contents of the Lovelace dashboard invisible.
After uninstalling and reinstalling the integration, I tried to create a new Irrigation card, but the card only shows the following error: 
this.lastChild.setConfig is not a function
**this.lastChild.setConfig is not a function**

**Comment by greentux** [comment]
While adding the card I cant choose the program. The error is
"Cannot read properties of undefined (reading 'attributes')"

**Comment by omenukas** [comment]
> While adding the card I cant choose the program. The error is "Cannot read properties of undefined (reading 'attributes')"

Now it's the same with me

**Comment by patfelst** [comment]
Should we delete the helpers we manually created before this release, and then do the update?

**Comment by petergridge** [comment]
> Should we delete the helpers we manually created before this release, and then do the update?

No, you will get a persistent notification letting you know what you can delete as part of the upgrade

**Comment by Crums30** [comment]
> After updating to V2025.01, all Irrigation cards disappeared. So impressive that it made the entire contents of the Lovelace dashboard invisible. After uninstalling and reinstalling the integration, I tried to create a new Irrigation card, but the card only shows the following error: this.lastChild.setConfig is not a function **this.lastChild.setConfig is not a function**

Same here.
I'm having the same message when trying to re-create the card.
Also, not sure how to add the adjustment factor. It does not seem to be created automatically like other helpers.

**Comment by petergridge** [comment]
> 2025-01-06 21:30:20.894 ERROR (MainThread) [frontend.js.modern.202501030] Uncaught error from Edge 131.0.0.0 on Windows 10
> TypeError: this.lastChild.setConfig is not a function
> set hass (/irrigationprogram/www/irrigation-card.js:296:20)
> ev.stopPropagation (src/panels/lovelace/cards/hui-card.ts:142:32)
> dispatchEvent (src/common/dom/fire_event.ts:75:7)
> customElements.get (src/panels/lovelace/create-element/create-element-base.ts:217:16)
> ![image](https://github.com/user-attachments/assets/9f970ae3-7c89-420f-88b2-cb46c30e72d1)
> 

Hi,  Can you send me the Diagnostics file. The help shows how to download it.

**Comment by patfelst** [comment]
> > Should we delete the helpers we manually created before this release, and then do the update?
> 
> No, you will get a persistent notification letting you know what you can delete as part of the upgrade
ok I will try upgrading soon

**Comment by petergridge** [comment]
> 2025-01-06 21:30:20.894 ERROR (MainThread) [frontend.js.modern.202501030] Uncaught error from Edge 131.0.0.0 on Windows 10
> TypeError: this.lastChild.setConfig is not a function
> set hass (/irrigationprogram/www/irrigation-card.js:296:20)
> ev.stopPropagation (src/panels/lovelace/cards/hui-card.ts:142:32)
> dispatchEvent (src/common/dom/fire_event.ts:75:7)
> customElements.get (src/panels/lovelace/create-element/create-element-base.ts:217:16)
> ![image](https://github.com/user-attachments/assets/9f970ae3-7c89-420f-88b2-cb46c30e72d1)
> 
Can you send me the diagnostic file, instructions are in the help file

**Comment by petergridge** [comment]
> After updating to V2025.01, all Irrigation cards disappeared. So impressive that it made the entire contents of the Lovelace dashboard invisible.
> After uninstalling and reinstalling the integration, I tried to create a new Irrigation card, but the card only shows the following error: 
> this.lastChild.setConfig is not a function
> **this.lastChild.setConfig is not a function**
> 
> 
Hi,  Can you send me the diagnostic file. 

Have you previously installed the standalone version of the card? You can see this from the resources page it will have two references to the card

**Comment by omenukas** [comment]
I have already deleted the integration, custom card from HACS and all old helpers. Then I reinstalled the integration with one program.
Now when I want to create a card, I see an empty card:
![image](https://github.com/user-attachments/assets/f9f04a7e-ad06-40c1-a684-a110fd78fe36)

**Comment by Crums30** [comment]
> > After updating to V2025.01, all Irrigation cards disappeared. So impressive that it made the entire contents of the Lovelace dashboard invisible.
> > After uninstalling and reinstalling the integration, I tried to create a new Irrigation card, but the card only shows the following error:
> > this.lastChild.setConfig is not a function
> > **this.lastChild.setConfig is not a function**
> 
> Hi, Can you send me the diagnostic file.
> 
> Have you previously installed the standalone version of the card? You can see this from the resources page it will have two references to the card

Here is my diagnostics file. 
[config_entry-irrigationprogram-01JGYT3XE4ZBKJN7SR76F3GV2A-4.json](https://github.com/user-attachments/files/18328443/config_entry-irrigationprogram-01JGYT3XE4ZBKJN7SR76F3GV2A-4.json)

**Comment by omenukas** [comment]
and here is my diagnostic file:
[config_entry-irrigationprogram-01JGZNA583J4M23YCC9X6WXWH8 (2).json](https://github.com/user-attachments/files/18328464/config_entry-irrigationprogram-01JGZNA583J4M23YCC9X6WXWH8.2.json)

**Comment by petergridge** [comment]
Can you try clearing the cache in your browser.

**Comment by greentux** [comment]
an my diagnostic json
[config_entry-irrigationprogram-01JGYAFMG75W4GV1J2K7MYF587.json](https://github.com/user-attachments/files/18328706/config_entry-irrigationprogram-01JGYAFMG75W4GV1J2K7MYF587.json)

**Comment by petergridge** [comment]
The card should look like this:
![image](https://github.com/user-attachments/assets/43e21493-37fd-4ad0-8a65-3989c2a987ee)
it no longer has the translation label data entry fields.

**Comment by Crums30** [comment]
> Can you try clearing the cache in your browser.

Done. Still same behaviour. I can add the card, but it appears briefly and the disappears with the same message this.lastChild.setConfig is not a function

**Comment by greentux** [comment]
and screenshot
![Bildschirmfoto zu 2025-01-07 07-55-07](https://github.com/user-attachments/assets/d4deabb8-bff2-42aa-89f2-26f9a241166f)

it is the extra card ( I tried after having the same problem with the integration only)

**Comment by petergridge** [comment]
can you screenshot the resources data for me:
![image](https://github.com/user-attachments/assets/65adb54f-05d0-42a3-a6c2-84d985e50609)
 System/dashboard then the hamburger and select resources

**Comment by petergridge** [comment]
Try this process:

# To remove this card and revert to the auto installed version follow this process.
* Delete the custom card and the HACS repository from your installation.
* Ensure the hacsfiles/irrigation-card/... resource is removed, delete it if required
* Upgrade to the latest version of the component V2024.10.01 or newer
* Restart HA
* Refresh the browser (you may need to clear the browser cache)
* Add the card to your HA Dashboard
* The card will be upgraded with each install of the component.

**Comment by Crums30** [comment]
> can you screenshot the resources data for me: ![image](https://private-user-images.githubusercontent.com/40281772/400666313-65adb54f-05d0-42a3-a6c2-84d985e50609.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYyMzMzNzksIm5iZiI6MTczNjIzMzA3OSwicGF0aCI6Ii80MDI4MTc3Mi80MDA2NjYzMTMtNjVhZGI1NGYtMDVkMC00MmEzLWE2YzItODRkOTg1ZTUwNjA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA3VDA2NTc1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViNjIzMTU3YjQ2YTRmZWE0YWVlYjI4MDM4ZWJkYzVkYmE0YTIyNjdlNjQyODMwYWE5ZDcxNThkZThhOWRmM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kUkvkgn1q3R9k0yXsIcs7tUFH0-YfCj63e9WCduKubw) System/dashboard then the hamburger and select resources

![Screenshot_2025-01-07-07-59-07-79_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/7212f5ee-08b0-40a1-9c0c-b96f81d72b44)

**Comment by greentux** [comment]
my ressources
![Bildschirmfoto zu 2025-01-07 08-00-39](https://github.com/user-attachments/assets/bda25eb4-312d-40f7-804c-f5add58796c6)

**Comment by greentux** [comment]
> Try this process:
> 
> # To remove this card and revert to the auto installed version follow this process.
> * Delete the custom card and the HACS repository from your installation.
> * Ensure the hacsfiles/irrigation-card/... resource is removed, delete it if required
> * Upgrade to the latest version of the component V2024.10.01 or newer
> * Restart HA
> * Refresh the browser (you may need to clear the browser cache)
> * Add the card to your HA Dashboard
> * The card will be upgraded with each install of the component.

What do You mean with "latest version of component"? the extra card  or the irrigation controller only?

**Comment by omenukas** [comment]
> Try this process:
> 
> # To remove this card and revert to the auto installed version follow this process.
> * Delete the custom card and the HACS repository from your installation.
> * Ensure the hacsfiles/irrigation-card/... resource is removed, delete it if required
> * Upgrade to the latest version of the component V2024.10.01 or newer
> * Restart HA
> * Refresh the browser (you may need to clear the browser cache)
> * Add the card to your HA Dashboard
> * The card will be upgraded with each install of the component.

That's how I did everything, but you didn't check for resources. I will try later as I have work now

**Comment by greentux** [comment]
> > Try this process:
> > # To remove this card and revert to the auto installed version follow this process.
> > 
> > * Delete the custom card and the HACS repository from your installation.
> > * Ensure the hacsfiles/irrigation-card/... resource is removed, delete it if required
> > * Upgrade to the latest version of the component V2024.10.01 or newer
> > * Restart HA
> > * Refresh the browser (you may need to clear the browser cache)
> > * Add the card to your HA Dashboard
> > * The card will be upgraded with each install of the component.
> 
> What do You mean with "latest version of component"? the extra card or the irrigation controller only?

Did all that.  Same ressources, same problem.

**Comment by greentux** [comment]
From the system protocoll

`Logger: frontend.js.modern.202411278
Quelle: components/system_log/__init__.py:331
Erstmals aufgetreten: 08:06:23 (2 Vorkommnisse)
Zuletzt protokolliert: 08:07:18

Uncaught error from Chrome 131.0.0.0 on Linux x86_64 TypeError: Cannot read properties of undefined (reading 'attributes') set hass (/irrigationprogram/www/irrigation-card.js:36:45) createCardElement (src/panels/lovelace/cards/hui-card.ts:126:27) ev.stopPropagation (src/panels/lovelace/cards/hui-card.ts:152:13) dispatchEvent (src/common/dom/fire_event.ts:76:7) tag.includes (src/panels/lovelace/create-element/create-element-base.ts:198:14)`

**Comment by omenukas** [comment]
I checked on my mobile phone, the program appeared, the card is new, but it shows the same error again.
![Screenshot_20250107_090835_Home Assistant](https://github.com/user-attachments/assets/7261c825-bac3-4c3e-851a-5c460fed4f05)

**Comment by Crums30** [comment]
> Try this process:
> 
> # To remove this card and revert to the auto installed version follow this process.
> * Delete the custom card and the HACS repository from your installation.
> * Ensure the hacsfiles/irrigation-card/... resource is removed, delete it if required
> * Upgrade to the latest version of the component V2024.10.01 or newer
> * Restart HA
> * Refresh the browser (you may need to clear the browser cache)
> * Add the card to your HA Dashboard
> * The card will be upgraded with each install of the component.

Did a fresh réinstalle like you mentionned. Still same.
Below two screenshots when créatine the card. First is right after I select the program, second is a couple of seconds later. The card seems OK, but this error then block the display. 
![Screenshot_2025-01-07-08-01-35-78_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/4265120d-eafb-4203-9975-475f2c8024e3)

![Screenshot_2025-01-07-08-01-38-87_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/5fff50df-7212-4772-ae29-cedd9dedb452)

**Comment by petergridge** [comment]
> > > Try this process:
> > > # To remove this card and revert to the auto installed version follow this process.
> > > 
> > > * Delete the custom card and the HACS repository from your installation.
> > > * Ensure the hacsfiles/irrigation-card/... resource is removed, delete it if required
> > > * Upgrade to the latest version of the component V2024.10.01 or newer
> > > * Restart HA
> > > * Refresh the browser (you may need to clear the browser cache)
> > > * Add the card to your HA Dashboard
> > > * The card will be upgraded with each install of the component.
> > 
> > 
> > What do You mean with "latest version of component"? the extra card or the irrigation controller only?
> 
> Did all that. Same ressources, same problem.

Irrigation component only, the card is deployed with the component automatically

**Comment by patfelst** [comment]
Worked first time for me. Installed the update, restarted HA, deleted the old helpers as per the persistent notification. Added new cards. All seems to be working! Looks much cleaner too.

When I reconfigured the programs, by default the start time options was blank. Had to select `Time selector`. Then when I applied I got an error. Not sure if this was becuase I had a couple of "Zone frequency replaces program frequency
", but I've decided to remove those overrides for now. After playing around repeating the config a few times, I eventually got the success message.

I'm using Rainbird so will let you know how it goes.

**Comment by archipita** [comment]
Hello,
I am having the same issue.
I have updated yesterday HA to 2025.1.0 and the integration to 2025.1.1 and got the same error in the card: "this.lastChild.setConfig is not a function". With the 2024.12 it was working.
What I have noticed is that if I try to modify the card, opening the settings, it shows very shortly the previous card layout and then the error is shown, replacing the rest. It seems a function called at the end that is messing up.

**Comment by petergridge** [comment]
Hi, what browser are you using? I can't recreate this issue in my environment

**Comment by petergridge** [comment]
I am using Chrome Version 131.0.6778.205 (Official Build) (64-bit)

**Comment by Crums30** [comment]
> Hi, what browser are you using? I can't recreate this issue in my environment

Using the Home Assistant app on Android, but it behaves the same with Chrome

**Comment by greentux** [comment]
Version 131.0.6778.139 (Offizieller Build) snap (64-Bit)

**Comment by omenukas** [comment]
> I am using Chrome Version 131.0.6778.205 (Official Build) (64-bit)


Same version of Chrome 131.0.6778.205 and Android app

**Comment by omenukas** [comment]
> Try this process:
> 
> # To remove this card and revert to the auto installed version follow this process.
> * Delete the custom card and the HACS repository from your installation.
> * Ensure the hacsfiles/irrigation-card/... resource is removed, delete it if required
> * Upgrade to the latest version of the component V2024.10.01 or newer
> * Restart HA
> * Refresh the browser (you may need to clear the browser cache)
> * Add the card to your HA Dashboard
> * The card will be upgraded with each install of the component.


I did all the points in Chrome browser. When adding a new card, it showed a good card for a second or two, but then showed the same error:


> Try this process:
> 
> # To remove this card and revert to the auto installed version follow this process.
> * Delete the custom card and the HACS repository from your installation.
> * Ensure the hacsfiles/irrigation-card/... resource is removed, delete it if required
> * Upgrade to the latest version of the component V2024.10.01 or newer
> * Restart HA
> * Refresh the browser (you may need to clear the browser cache)
> * Add the card to your HA Dashboard
> * The card will be upgraded with each install of the component.

I did all the points in Chrome browser. When adding a new card, it showed a good card for a second or two, but then showed the same error:
![image](https://github.com/user-attachments/assets/f560e85b-7372-47d0-a243-0d9573685a90)

**Comment by petergridge** [comment]
I have released V2025.01.02b1 with some changes that may help, again it works for me but without the same failures it is impossible to tell. 🤞

**Comment by greentux** [comment]
Ok will check late afternoon. I could offer a remote session too...

**Comment by omenukas** [comment]
> I have released V2025.01.02b1 with some changes that may help, again it works for me but without the same failures it is impossible to tell. 🤞

I repeated the whole process from the beginning....same thing, nothing changed

**Comment by greentux** [comment]
may it depends on HOAS version? Im on latest 24 back. Not using 25 in the moment.

**Comment by omenukas** [comment]
> That is frustrating, I will add some debug output into the Javascript and see if we can identify some clues to the problem. Time for met to sign off for the night will try some more tomorrow afternoon.

It's good that it's winter and watering is not needed now :)

**Comment by petergridge** [comment]
I am on 2025.01 but this was all developed on 2024.12, there have been 450 downloads and the 20 or so beta testers did not report this issue, it is a HTML DOM element issue. I don't have a lot of experience with the front end development so it is amazing that the Card has not had bigger issues earlier 😃

**Comment by omenukas** [comment]
To be honest, I haven't opened Irrigation cards since the watering season ended and maybe it stopped working before...I can't say. I noticed yesterday when the helper messages appeared after the integration update

**Comment by Crums30** [comment]
I switched to HA 2025.1 and everything was showing OK on my dashboard, so I assume it was working. I guess it stopped working when I updated the Irrigation integration couple of days after.

**Comment by archipita** [comment]
> Hi, what browser are you using? I can't recreate this issue in my environment

I am on Firefox (v133), but the same happens with Chrome.

**Comment by greentux** [comment]
Ok, after upgrading to the latest Beta I can add the card.
But I cant see any Zone config. One Zone ist defined.

![Bildschirmfoto zu 2025-01-07 19-54-12](https://github.com/user-attachments/assets/c49c1a06-0ea7-4e49-9195-ea314a5ad6bc)

**Comment by greentux** [comment]
Ah sorry. The card has "config" options. Now all works fine for me.

**Comment by omenukas** [comment]
> Ah sorry. The card has "config" options. Now all works fine for me.

for me and with the Beta version, it shows a good card for a few seconds, but then says "this.lastElementChild.setConfig is not a function"

**Comment by Crums30** [comment]
Same here. Still the same issue with the bêta version

**Comment by omenukas** [comment]
Interestingly, not everyone has this problem.
My installation:
VM on Proxmox
Core                             2025.1.1
Supervisor                   2024.12.3
Operating System       14.1
Front end                    20250106.0 

Irrigation integration   V2025.01.02b1

Tested on:
Microsoft Edge          131.0.2903.112
Google Chrome         131.0.6778.265
Firefox                        134.0
Android Companion app

**Comment by petergridge** [comment]
Version V2025.01.02b20 released, I hope I am on the right track to resolve this one. I did find an error in the javascript logging and corrected it.

**Comment by Crums30** [comment]
> Version V2025.01.02b20 released, I hope I am on the right track to resolve this one. I did find an error in the javascript logging and corrected it.

Hi Peter,

Thanks for working hard on this one.
Unfortunately after a fresh reinstall of last beta release, it still behaves the same....
Quick preview of the card (which looks very nice indeed) and and the same error replaces it after couple of seconds....

**Comment by petergridge** [comment]
Version V2025.01.02b23 released, don't forget to refresh your browser after updating

**Comment by Crums30** [comment]
> Version V2025.01.02b23 released, don't forget to refresh your browser after updating

Hi Peter. No change with V2025.01.02b23 Unfortunately...

**Comment by petergridge** [comment]
> > Version V2025.01.02b23 released, don't forget to refresh your browser after updating
> 
> Hi Peter. No change with V2025.01.02b23 Unfortunately...

can you check a few things for me:

In CHROME:

1. refresh the browser <F5>
2. open the developer tool: <ctrl><shift><i>
3. clear the log 
<img width="256" alt="image" src="https://github.com/user-attachments/assets/6ee3a5bb-7c67-4e07-b506-c8feb40cd201" />
4. add the custom card
5. screen shot the console details
<img width="1333" alt="image" src="https://github.com/user-attachments/assets/67fc49ed-b539-46e1-a985-068fb5f2816a" />

If possible a teamviewer session so I can see what is happening on your end

**Comment by omenukas** [comment]
with version 23b card started working.
Maybe I'm not good yet and I don't understand how to use it, but the "Power" and "Settings" buttons on my card are inactive, the "Enable" switch turns off immediately after turning it on:

![image](https://github.com/user-attachments/assets/ab64f74c-460b-4e32-ad87-1d9885244d7c)

**Comment by petergridge** [comment]
Can you check the system log for errors,

**Comment by omenukas** [comment]
I understood the point - the buttons work, but you just need to refresh the browser to see the changed status

**Comment by petergridge** [comment]
Is that everytime you change the switch?

**Comment by omenukas** [comment]
> Is that everytime you change the switch?

Yes

**Comment by petergridge** [comment]
Ok, that is not expected

**Comment by omenukas** [comment]
> Ok, that is not expected

When pressing the buttons through the Android app, the changes are visible only after closing the app, clearing the cache and re-opening the app.

**Comment by petergridge** [comment]
> > Ok, that is not expected
> 
> When pressing the buttons through the Android app, the changes are visible only after closing the app, clearing the cache and re-opening the app.

Can you run through debug process I sent for CHROME there may be some clues there

**Comment by omenukas** [comment]
> > > Ok, that is not expected
> > 
> > 
> > When pressing the buttons through the Android app, the changes are visible only after closing the app, clearing the cache and re-opening the app.
> 
> Can you run through debug process I sent for CHROME there may be some clues there

I don't know how :) If you could explain, I would try it

**Comment by petergridge** [comment]
Hi another version has been released, I am really clutching at straws (wet paper ones at that 😃) now.

**Comment by petergridge** [comment]
> > > > Ok, that is not expected
> > > 
> > > 
> > > When pressing the buttons through the Android app, the changes are visible only after closing the app, clearing the cache and re-opening the app.
> > 
> > 
> > Can you run through debug process I sent for CHROME there may be some clues there
> 
> I don't know how :) If you could explain, I would try it

In CHROME:

After installing the latest version.

1. refresh the browser F5
2. open the developer tool: ctrl+shift+i
3. clear the log 
<img width="256" alt="image" src="https://github.com/user-attachments/assets/6ee3a5bb-7c67-4e07-b506-c8feb40cd201" />
4. refresh the browser again
5. screen shot the console details
<img width="1333" alt="image" src="https://github.com/user-attachments/assets/67fc49ed-b539-46e1-a985-068fb5f2816a" />

**Comment by omenukas** [comment]
here is with version 23b
![image](https://github.com/user-attachments/assets/bb19e7bd-4b5e-4669-b510-72aa4aa48436)

**Comment by petergridge** [comment]
Thanks, can you try it with the newer version

**Comment by Crums30** [comment]
> new b60 version not working...same as before 

Same for me. I managed to get version b23 working but with the same issue when trying to change a parameter or clic a button, need to refresh the page. 

With version b60, im back with error message

**Comment by filski** [comment]
Just FYI, I also had a problem with the card in the new version. It was something like "Cannot read properties of undefined (reading 'length')" - not sure exactly, didn't get a screenshot. In any case, I restored to the previous version for now.

**Comment by petergridge** [comment]
> Just FYI, I also had a problem with the card in the new version. It was something like "Cannot read properties of undefined (reading 'length')" - not sure exactly, didn't get a screenshot. In any case, I restored to the previous version for now.

Can you check that you only have the current version of the custom card installed. Some people have installed the stand alone version of the card and that needs to be removed manually.

**Comment by omenukas** [comment]
Another important observation is that after downloading the resource from HACS, you cannot restart HA, as required by the system, because then the added irrigation programs will not really work. You need to add programs first and only then restart HA

**Comment by petergridge** [comment]
Hi All, I have not had much luck resolving the issue with the card. 

A bit of technical background. the Custom card is simply leveraging the entities card and programmatically populating the configuration to. For some reason this is not working as well as previously and some of you are experiencing the issues documented above.

As a work around I have added code to generate the yaml required to implement the card for each defined program and expose it in a notification.

- Copy the script from the notification into a manual card replacing any text present in the card.
- When saved a entities card is created with the same interface as the custom card.
- The script will be regenerated each time the irrigation program is modified and on restart
 
![image](https://github.com/user-attachments/assets/49e03380-f873-4e4f-b011-ea37a0bc5aff)
![image](https://github.com/user-attachments/assets/e1d99cc7-4aab-4e16-9ecf-76dacd0451d0)
![image](https://github.com/user-attachments/assets/b56b9b86-0b44-4fc5-b216-6802f5523af9)
![image](https://github.com/user-attachments/assets/240758e1-f97c-474d-9570-b773a703cd85)

**Comment by omenukas** [comment]
Which version to install?

**Comment by Crums30** [comment]
> Which version to install?

Last beta : 2025.01. 03b1

Peter, just tested. That's working fine !!!!
Thanks for this 👏

**Comment by omenukas** [comment]
works for me too

**Comment by patfelst** [comment]
FYI I wasn't having card problems, but tried the yaml from the notification so I could try and adjust the "time remaining" entity display format. So I've got both versions of the cards running in two separate HA tabs.

So the new manual card appears ok, but when I turn on a zone, a few things don't seem to be working (see screen shot below):
- zone status says it's off
- The icon changes to a water drop (doesn't do the stopwatch for a brief moment, then change to a sprinkler)
- The time remaining doesn't appear

Note that the actual sprinker valve physically does turn on.

<img width="448" alt="image" src="https://github.com/user-attachments/assets/ae15b64e-8412-44b3-a31d-041d67be828d" />

**Comment by patfelst** [comment]
Just noticed if I run the program, I get a slightly different result

<img width="448" alt="image" src="https://github.com/user-attachments/assets/193f6c9d-807d-4b6e-88cb-135822589132" />

**Comment by omenukas** [comment]
Maybe you can explain me how to add the rain sensor. I have an Ecowitt rain sensor and in the old version I had added an input boolean sensor. And what to do now?

**Comment by petergridge** [comment]
> Maybe you can explain me how to add the rain sensor. I have an Ecowitt rain sensor and in the old version I had added an input boolean sensor. And what to do now?

Hi omenuka, can you start a new issue, this one is getting to many variations and it is hard to keep track.

**Comment by omenukas** [comment]
> > Maybe you can explain me how to add the rain sensor. I have an Ecowitt rain sensor and in the old version I had added an input boolean sensor. And what to do now?
> 
> Hi omenuka, can you start a new issue, this one is getting to many variations and it is hard to keep track.

ok
Close this issue or will you still try to solve the card problem?

**Comment by petergridge** [comment]
I will leave this issue active for a little while, I am fixing some related problems with the yaml.

**Comment by petergridge** [comment]
V2025.01.03b2 is released
- fixed a few inconsistencies between the yaml and the custom card
- added config flow option in the advanced menu to enable/disable the yaml generation.

**Comment by patfelst** [comment]
thanks Peter, that's fixed the zone time remaining stuff, but I notice the first row of the program is now missing:
<img width="1412" alt="image" src="https://github.com/user-attachments/assets/7ce78b3f-3935-4b43-98e0-c621a130bee1" />
i.e. there's no program on/off button, or the "settings" show/hide.
Thanks

**Comment by petergridge** [comment]
V2025.01.03.b3 released, fix one break one, just trying to keep myself busy 😃

**Comment by patfelst** [comment]
I think what's happening is the very first notifications after downloading the update work ok, but subsequent notifications are still missing the first row :(

**Comment by patfelst** [comment]
actually I am on the right version, its just the label hasn't been updated
<img width="1218" alt="image" src="https://github.com/user-attachments/assets/55ac472a-a853-41a6-9359-5650151a9d2c" />
but in HACS I see I'm on the latest
<img width="984" alt="image" src="https://github.com/user-attachments/assets/6704ab03-cb16-4f40-9db7-728e1ee996b2" />

**Comment by omenukas** [comment]
V2025.01.03.b3, seems to be fine
![image](https://github.com/user-attachments/assets/04bce94f-7f53-4a76-a8d5-03c61e856500)

**Comment by patfelst** [comment]
can you try generating and pasting the yaml again? Like I said it works the first time. subsequent times for me, miss the first row of each card.

**Comment by omenukas** [comment]
Yes, the top row really disappears. But the question is, is it necessary to generate the yaml a second time? As far as I have tried now, if I change the settings in "Configure", it also changes in the existing card
![image](https://github.com/user-attachments/assets/820fc342-a168-4177-8d4b-e7cc867f4a88)

**Comment by patfelst** [comment]
thanks for confirming. Peter has added an advanced option to generate the yaml each time you reconfigure a program, so yes I think it should work properly, for example, what if you wanted to move a zone from one program to another? You need to regenerate.

**Comment by petergridge** [comment]
Just noting I did not update the manifest on this so the HA version will be out of sync with the HACS version. Until I go to the full release with V2025.01.03.

Are there any remaining issues with the latest version that need to be addressed before I move this version off BETA

**Comment by omenukas** [comment]
> Just noting I did not update the manifest on this so the HA version will be out of sync with the HACS version. Until I go to the full release with V2025.01.03.
> 
> Are there any remaining issues with the latest version that need to be addressed before I move this version off BETA

since my programs are completely basic and I only use one rain sensor, and it's winter at the moment, I don't see any problems at the moment.

**Comment by patfelst** [comment]
> HA version will be out of sync with the HACS version

Is there a HA version? I thought HACS was the only way to install. Or do you mean the HACS released vs beta are out of sync?

**Comment by omenukas** [comment]
> > HA version will be out of sync with the HACS version
> 
> Is there a HA version? I thought HACS was the only way to install. Or do you mean the HACS released vs beta are out of sync?
> 
> And no other issues, it seems to be working fine for me for the last few days, and it's hot here in Adelaide South Australia.

Need to come to your house to check how the watering works :D :D

**Comment by petergridge** [comment]
The manifest file version number is used here
![image](https://github.com/user-attachments/assets/52b97133-dfaf-4085-9658-cfa0d219c605)
and the GITHUB version is used in HACS

It's wet in Sydney, I am not missing the 47 degrees we had while in Perth though.

Thanks for the confirmation I will finalise the release.

**Comment by petergridge** [comment]
I have a simple system, just four zones. ECO feature for pots, openweathermaphistory for managing the wet days. I built my controller based on an ESP an IO expander and some solid state relays, it cost more for the box it is in than the parts.

I don't use most of the features these have grown as a result of requests over the years. Every time I think there is no more possible requirements people find one and the use cases make sense so I extend the functionality. Every year or so I have done a big release implementing some new skills I have learnt along the way. There are users all over, Europe and North America appear to be the most active. What I really need are people to help with the translations.

**Comment by omenukas** [comment]
> I have a simple system, just four zones. ECO feature for pots, openweathermaphistory for managing the wet days. I built my controller based on an ESP an IO expander and some solid state relays, it cost more for the box it is in than the parts.
> 
> I don't use most of the features these have grown as a result of requests over the years. Every time I think there is no more possible requirements people find one and the use cases make sense so I extend the functionality. Every year or so I have done a big release implementing some new skills I have learnt along the way. There are users all over, Europe and North America appear to be the most active. What I really need are people to help with the translations.

My native language is Lithuanian, HA is also Lithuanian, but we have already come to terms with the fact that there are no normal translations:)

**Comment by omenukas** [comment]
in terms of functionality, the old version was better for me because I could use the input boolean sensor for the rain sensor. With Node Red, I made the on/off connection of this sensor according to the rain sensor's day and current situation values. Now I can only add one and will have to think about how to use both sensors.

**Comment by patfelst** [comment]
Maybe we should have a "show your system" issue, or github "discussion". Anyway, I'm on a 1030m2 block of land with 8 zones! Zone 1, 2, 3, 7 and 8 are lawn sprinklers, zones 4, 5 and 6 are garden bed drippers.
<img width="1604" alt="image" src="https://github.com/user-attachments/assets/55dceeae-f32f-46c8-8648-baa05a02de1f" />

Photo is of zones 1, 2 and 3 (back lawns and garden bed) taken just now.

![IMG_0342](https://github.com/user-attachments/assets/4493716b-c093-41af-9ec0-6f0e005978b3)

I have a Rainbird controller with the WiFi plug in adapter. I integrated it with HA because the performance of the Rainbird iPhone app is terrible. When you first open the app it takes 20-30 sec to connect, but it often just fails. Then once you're in, the app response is bad. I'm pretty sure the problems are with the Rainbird cloud as the wifi signal strength is very good. So now I don't use the app, and leave the Rainbird on manual, everything is controlled from HA using your integration.

I plan to replace with Rainbird with a controller I built based on [this relay board](https://lilygo.cc/products/t-relay-5v-8-channel-relay) which has an integrated ESP32. I installed ESPHome on it to integrate with HA. Have not finished the project due to concerns with the mains wiring side of things (solenoids are 24 VAC).

**Comment by petergridge** [comment]
That looks great, you have a beautiful garden. 

I am using a 24vac power supply, and a 24ac to 5vdc conversion to power the esp. I had a board printed to carry most of the parts so it looks neat. THe power side I used off the shelf components. I have had some mechanical relays fail on me in the past so opted for solid state. These work well with AC. 

Looking at your board, I don't see any issues, not that I am an electrician, a 12V DC power supply to run the board, and you will be able to reuse the 24VAC from the rainbird for the solenoid side, the 24VAC was commonly used for garden lighting etc in the past less loss over distance I believe.

**Comment by Lucky51179** [comment]
Hello, my Rainbird controller is not working and is not being addressed. I can manually turn on the sprinklers.

**Comment by petergridge** [comment]
Hi, can you confirm that you can start the solenoid using the service exposed by the rainbird component.

https://www.home-assistant.io/integrations/rainbird/

**Comment by patfelst** [comment]
Just another data point, my Rainbird is working ok

**Comment by Lucky51179** [comment]
Hello, the valves have been running for a short time and I can no longer activate them.
——————————————————

Thomas Serwuschok
Bei den Pfalzwiesen 15
90556 Cadolzburg/ Egersdorf

Telefon: 091037156701
Handy 0151 705 515 46

> Am 03.05.2025 um 07:43 schrieb Peter ***@***.***>:
> 
> Hi, can you confirm that you can start the solenoid using the service exposed by the rainbird component.
